/*
 Copyright (c) 2011~2013 Humu <humu2009@gmail.com>
 This file is part of jsc3d project, which is freely distributable under the
 terms of the MIT license.

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 THE SOFTWARE.
*/
var JSC3D=JSC3D||{};
JSC3D.Viewer=function(a,b){this.params=b?{SceneUrl:b.SceneUrl||"",InitRotationX:b.InitRotationX||0,InitRotationY:b.InitRotationY||0,InitRotationZ:b.InitRotationZ||0,ModelColor:b.ModelColor||"#caa618",BackgroundColor1:b.BackgroundColor1||"#ffffff",BackgroundColor2:b.BackgroundColor2||"#383840",BackgroundImageUrl:b.BackgroundImageUrl||"",RenderMode:b.RenderMode||"flat",Definition:b.Definition||"standard",MipMapping:b.MipMapping||"off",CreaseAngle:b.parameters||-180,SphereMapUrl:b.SphereMapUrl||"",ProgressBar:b.ProgressBar||
"on",Renderer:b.Renderer||"",LocalBuffers:b.LocalBuffers||"retain"}:{SceneUrl:"",InitRotationX:0,InitRotationY:0,InitRotationZ:0,ModelColor:"#caa618",BackgroundColor1:"#ffffff",BackgroundColor2:"#383840",BackgroundImageUrl:"",RenderMode:"flat",Definition:"standard",MipMapping:"off",CreaseAngle:-180,SphereMapUrl:"",ProgressBar:"on",Renderer:"",LocalBuffers:"retain"};this.canvas=a;this.selectionBuffer=this.zBuffer=this.colorBuffer=this.bkgColorBuffer=this.canvasData=this.ctx=null;this.frameWidth=a.width;
this.frameHeight=a.height;this.sphereMap=this.defaultMaterial=this.scene=null;this.isFailed=this.isLoaded=!1;this.abortUnfinishedLoadingFn=null;this.needRepaint=this.needUpdate=!1;this.initRotZ=this.initRotY=this.initRotX=0;this.zoomFactor=1;this.panning=[0,0];this.rotMatrix=new JSC3D.Matrix3x4;this.transformMatrix=new JSC3D.Matrix3x4;this.sceneUrl="";this.modelColor=13280792;this.bkgColor1=16777215;this.bkgColor2=3684416;this.bkgImageUrl="";this.bkgImage=null;this.renderMode="flat";this.definition=
"standard";this.isMipMappingOn=!1;this.creaseAngle=-180;this.sphereMapUrl="";this.showProgressBar=!0;this.buttonStates={};this.keyStates={};this.mouseY=this.mouseX=0;this.isTouchHeld=!1;this.baseZoomFactor=1;this.afterupdate=this.beforeupdate=this.onmousewheel=this.onmousemove=this.onmouseup=this.onmousedown=this.onloadingerror=this.onloadingaborted=this.onloadingprogress=this.onloadingcomplete=this.onloadingstarted=null;this.mouseUsage="default";this.isDefaultInputHandlerEnabled=!0;this.webglBackend=
this.messagePanel=this.progressRectangle=this.progressFrame=null;this.lastRotY=this.lastRotX=0;var c=this;this.canvas.addEventListener("mousedown",function(a){c.mouseDownHandler(a)},!1);this.canvas.addEventListener("mouseup",function(a){c.mouseUpHandler(a)},!1);this.canvas.addEventListener("mousemove",function(a){c.mouseMoveHandler(a)},!1);this.canvas.addEventListener("firefox"==JSC3D.PlatformInfo.browser?"DOMMouseScroll":"mousewheel",function(a){c.mouseWheelHandler(a)},!1);document.addEventListener("keydown",
function(a){c.keyDownHandler(a)},!1);document.addEventListener("keyup",function(a){c.keyUpHandler(a)},!1);this.canvas.addEventListener("touchstart",function(a){c.touchStartHandler(a)},!1);this.canvas.addEventListener("touchend",function(a){c.touchEndHandler(a)},!1);this.canvas.addEventListener("touchmove",function(a){c.touchMoveHandler(a)},!1)};JSC3D.Viewer.prototype.setParameter=function(a,b){this.params[a]=b};
JSC3D.Viewer.prototype.init=function(){this.sceneUrl=this.params.SceneUrl;this.initRotX=parseFloat(this.params.InitRotationX);this.initRotY=parseFloat(this.params.InitRotationY);this.initRotZ=parseFloat(this.params.InitRotationZ);this.modelColor=parseInt("0x"+this.params.ModelColor.substring(1));this.bkgColor1=parseInt("0x"+this.params.BackgroundColor1.substring(1));this.bkgColor2=parseInt("0x"+this.params.BackgroundColor2.substring(1));this.bkgImageUrl=this.params.BackgroundImageUrl;this.renderMode=
this.params.RenderMode.toLowerCase();this.definition=this.params.Definition.toLowerCase();this.creaseAngle=parseFloat(this.params.CreaseAngle);this.isMipMappingOn="on"==this.params.MipMapping.toLowerCase();this.sphereMapUrl=this.params.SphereMapUrl;this.showProgressBar="on"==this.params.ProgressBar.toLowerCase();this.useWebGL="webgl"==this.params.Renderer.toLowerCase();this.releaseLocalBuffers="release"==this.params.LocalBuffers.toLowerCase();if(this.useWebGL&&JSC3D.PlatformInfo.supportWebGL&&JSC3D.WebGLRenderBackend)try{this.webglBackend=
new JSC3D.WebGLRenderBackend(this.canvas,this.releaseLocalBuffers)}catch(b){}if(!this.webglBackend){this.useWebGL&&JSC3D.console&&JSC3D.console.logWarning("WebGL is not available. Software rendering is enabled instead.");try{this.ctx=this.canvas.getContext("2d"),this.canvasData=this.ctx.getImageData(0,0,this.canvas.width,this.canvas.height)}catch(b){this.canvasData=this.ctx=null}}if(2>=this.canvas.width||2>=this.canvas.height)this.definition="standard";switch(this.definition){case "low":this.frameWidth=
~~((this.canvas.width+1)/2);this.frameHeight=~~((this.canvas.height+1)/2);break;case "high":this.frameWidth=2*this.canvas.width;this.frameHeight=2*this.canvas.height;break;default:this.frameWidth=this.canvas.width,this.frameHeight=this.canvas.height}this.zoomFactor=1;this.panning=[0,0];this.rotMatrix.identity();this.transformMatrix.identity();this.needRepaint=this.needUpdate=this.isFailed=this.isLoaded=!1;this.scene=null;this.defaultMaterial=new JSC3D.Material;this.defaultMaterial.ambientColor=0;
this.defaultMaterial.diffuseColor=this.modelColor;this.defaultMaterial.transparency=0;this.defaultMaterial.simulateSpecular=!0;this.webglBackend||(this.colorBuffer=Array(this.frameWidth*this.frameHeight),this.zBuffer=Array(this.frameWidth*this.frameHeight),this.selectionBuffer=Array(this.frameWidth*this.frameHeight),this.bkgColorBuffer=Array(this.frameWidth*this.frameHeight));this.generateBackground();this.drawBackground();var a=this;(function c(){a.doUpdate();setTimeout(c,30)})();this.setBackgroudImageFromUrl(this.bkgImageUrl);
this.loadScene();this.setSphereMapFromUrl(this.sphereMapUrl)};JSC3D.Viewer.prototype.update=function(a){this.isFailed||(a?this.needRepaint=!0:this.needUpdate=!0)};JSC3D.Viewer.prototype.rotate=function(a,b,c){this.rotMatrix.rotateAboutXAxis(a);this.rotMatrix.rotateAboutYAxis(b);this.rotMatrix.rotateAboutZAxis(c)};JSC3D.Viewer.prototype.setRenderMode=function(a){this.renderMode=this.params.RenderMode=a};
JSC3D.Viewer.prototype.setDefinition=function(a){if(2>=this.canvas.width||2>=this.canvas.height)a="standard";if(a!=this.definition){this.definition=this.params.Definition=a;a=this.frameWidth;switch(this.definition){case "low":this.frameWidth=~~((this.canvas.width+1)/2);this.frameHeight=~~((this.canvas.height+1)/2);break;case "high":this.frameWidth=2*this.canvas.width;this.frameHeight=2*this.canvas.height;break;default:this.frameWidth=this.canvas.width,this.frameHeight=this.canvas.height}a=this.frameWidth/
a;this.zoomFactor*=a;this.panning[0]*=a;this.panning[1]*=a;this.webglBackend||(a=this.frameWidth*this.frameHeight,this.colorBuffer.length<a&&(this.colorBuffer=Array(a)),this.zBuffer.length<a&&(this.zBuffer=Array(a)),this.selectionBuffer.length<a&&(this.selectionBuffer=Array(a)),this.bkgColorBuffer.length<a&&(this.bkgColorBuffer=Array(a)),this.generateBackground())}};
JSC3D.Viewer.prototype.setBackgroudImageFromUrl=function(a){this.bkgImageUrl=this.params.BackgroundImageUrl=a;if(""==a)this.bkgImage=null;else{var b=this,c=new Image;c.onload=function(){b.bkgImage=this;b.generateBackground()};c.src=a}};JSC3D.Viewer.prototype.setSphereMapFromUrl=function(a){this.sphereMapUrl=this.params.SphereMapUrl=a;if(""==a)this.sphereMap=null;else{var b=this,c=new JSC3D.Texture;c.onready=function(){b.sphereMap=c;b.update()};c.createFromUrl(this.sphereMapUrl)}};
JSC3D.Viewer.prototype.enableDefaultInputHandler=function(a){this.isDefaultInputHandlerEnabled=a};JSC3D.Viewer.prototype.setMouseUsage=function(a){this.mouseUsage=a};JSC3D.Viewer.prototype.isWebGLEnabled=function(){return null!=this.webglBackend};JSC3D.Viewer.prototype.replaceSceneFromUrl=function(a,b){this.sceneUrl=this.params.SceneUrl=a;this.isFailed=this.isLoaded=!1;this.loadScene(b)};
JSC3D.Viewer.prototype.replaceScene=function(a){this.sceneUrl=this.params.SceneUrl="";this.isFailed=!1;this.isLoaded=!0;this.setupScene(a)};JSC3D.Viewer.prototype.resetScene=function(){var a=!this.scene||this.scene.isEmpty()?0:this.scene.aabb.lengthOfDiagonal();this.zoomFactor=0==a?1:(this.frameWidth<this.frameHeight?this.frameWidth:this.frameHeight)/a;this.panning=[0,0];this.rotMatrix.identity();this.rotMatrix.rotateAboutXAxis(this.initRotX);this.rotMatrix.rotateAboutYAxis(this.initRotY);this.rotMatrix.rotateAboutZAxis(this.initRotZ)};
JSC3D.Viewer.prototype.getScene=function(){return this.scene};
JSC3D.Viewer.prototype.pick=function(a,b){var c=new JSC3D.PickInfo,d=this.canvas.getBoundingClientRect(),e=a-d.left;d=b-d.top;c.canvasX=e;c.canvasY=d;var f=0;if(this.webglBackend)f=this.webglBackend.pick(e,d);else{var g=e,h=d;if(null!=this.selectionBuffer&&0<=e&&e<this.canvas.width&&0<=d&&d<this.canvas.height){switch(this.definition){case "low":g=~~(g/2);h=~~(h/2);break;case "high":g*=2,h*=2}f=this.selectionBuffer[h*this.frameWidth+g];0<f&&(c.depth=this.zBuffer[h*this.frameWidth+g])}}if(0<f)for(var k=
this.scene.getChildren(),l=0;l<k.length;l++)if(k[l].internalId==f){c.mesh=k[l];break}c.canvasX=e;c.canvasY=d;c.mesh&&(c.depth=this.zBuffer[h*this.frameWidth+g]);return c};
JSC3D.Viewer.prototype.doUpdate=function(){if(this.needUpdate||this.needRepaint)null!=this.beforeupdate&&"function"==typeof this.beforeupdate&&this.beforeupdate(),this.scene?(this.needUpdate&&(this.beginScene(),this.render(),this.endScene()),this.paint()):this.drawBackground(),this.needUpdate=this.needRepaint=!1,null!=this.afterupdate&&"function"==typeof this.afterupdate&&this.afterupdate()};
JSC3D.Viewer.prototype.paint=function(){!this.webglBackend&&this.ctx&&this.ctx.putImageData(this.canvasData,0,0)};JSC3D.Viewer.prototype.mouseDownHandler=function(a){if(this.isLoaded){if(this.onmousedown){var b=this.pick(a.clientX,a.clientY);this.onmousedown(b.canvasX,b.canvasY,a.button,b.depth,b.mesh)}a.preventDefault();a.stopPropagation();this.isDefaultInputHandlerEnabled&&(this.buttonStates[a.button]=!0,this.mouseX=a.clientX,this.mouseY=a.clientY)}};
JSC3D.Viewer.prototype.mouseUpHandler=function(a){if(this.isLoaded){if(this.onmouseup){var b=this.pick(a.clientX,a.clientY);this.onmouseup(b.canvasX,b.canvasY,a.button,b.depth,b.mesh)}a.preventDefault();a.stopPropagation();this.isDefaultInputHandlerEnabled&&(this.buttonStates[a.button]=!1)}};
JSC3D.Viewer.prototype.mouseMoveHandler=function(a){if(this.isLoaded){if(this.onmousemove){var b=this.pick(a.clientX,a.clientY);this.onmousemove(b.canvasX,b.canvasY,a.button,b.depth,b.mesh)}a.preventDefault();a.stopPropagation();if(this.isDefaultInputHandlerEnabled){b=1==this.keyStates[16];var c=1==this.keyStates[17];if(1==this.buttonStates[0]){if(b&&"default"==this.mouseUsage||"zoom"==this.mouseUsage)this.zoomFactor*=this.mouseY<=a.clientY?1.04:.96;else if(c&&"default"==this.mouseUsage||"pan"==this.mouseUsage)b=
"low"==this.definition?.5:"high"==this.definition?2:1,this.panning[0]+=b*(a.clientX-this.mouseX),this.panning[1]+=b*(a.clientY-this.mouseY);else if("default"==this.mouseUsage||"rotate"==this.mouseUsage)b=360*(a.clientX-this.mouseX)/this.canvas.height,this.rotMatrix.rotateAboutXAxis(360*(a.clientY-this.mouseY)/this.canvas.width),this.rotMatrix.rotateAboutYAxis(b);this.mouseX=a.clientX;this.mouseY=a.clientY;this.update()}}}};
JSC3D.Viewer.prototype.mouseWheelHandler=function(a){if(this.isLoaded){if(this.onmousewheel){var b=this.pick(a.clientX,a.clientY);this.onmousewheel(b.canvasX,b.canvasY,a.button,b.depth,b.mesh)}a.preventDefault();a.stopPropagation();this.isDefaultInputHandlerEnabled&&(this.zoomFactor*=0>("firefox"==JSC3D.PlatformInfo.browser?-a.detail:a.wheelDelta)?1.1:.91,this.update())}};
JSC3D.Viewer.prototype.touchStartHandler=function(a){if(this.isLoaded&&0<a.touches.length){var b=a.touches[0].clientX,c=a.touches[0].clientY;if(this.onmousedown){var d=this.pick(b,c);this.onmousedown(d.canvasX,d.canvasY,0,d.depth,d.mesh)}a.preventDefault();a.stopPropagation();this.isDefaultInputHandlerEnabled&&(this.buttonStates[0]=!0,this.mouseX=b,this.mouseY=c)}};
JSC3D.Viewer.prototype.touchEndHandler=function(a){if(this.isLoaded){if(this.onmouseup){var b=this.pick(this.mouseX,this.mouseY);this.onmouseup(b.canvasX,b.canvasY,0,b.depth,b.mesh)}a.preventDefault();a.stopPropagation();this.isDefaultInputHandlerEnabled&&(this.buttonStates[0]=!1)}};
JSC3D.Viewer.prototype.touchMoveHandler=function(a){if(this.isLoaded&&0<a.touches.length){var b=a.touches[0].clientX,c=a.touches[0].clientY;if(this.onmousemove){var d=this.pick(b,c);this.onmousemove(d.canvasX,d.canvasY,0,d.depth,d.mesh)}a.preventDefault();a.stopPropagation();if(this.isDefaultInputHandlerEnabled){if("zoom"==this.mouseUsage)this.zoomFactor*=this.mouseY<=c?1.04:.96;else if("pan"==this.mouseUsage)a="low"==this.definition?.5:"high"==this.definition?2:1,this.panning[0]+=a*(b-this.mouseX),
this.panning[1]+=a*(c-this.mouseY);else if("default"==this.mouseUsage||"rotate"==this.mouseUsage)a=360*(b-this.mouseX)/this.canvas.height,this.rotMatrix.rotateAboutXAxis(360*(c-this.mouseY)/this.canvas.width),this.rotMatrix.rotateAboutYAxis(a);this.mouseX=b;this.mouseY=c;this.update()}}};JSC3D.Viewer.prototype.keyDownHandler=function(a){this.isDefaultInputHandlerEnabled&&(this.keyStates[a.keyCode]=!0)};
JSC3D.Viewer.prototype.keyUpHandler=function(a){this.isDefaultInputHandlerEnabled&&(this.keyStates[a.keyCode]=!1)};
JSC3D.Viewer.prototype.gestureHandler=function(a){if(this.isLoaded){var b=a.gesture.center.pageX-document.body.scrollLeft,c=a.gesture.center.pageY-document.body.scrollTop,d=this.pick(b,c);switch(a.type){case "touch":if(this.onmousedown)this.onmousedown(d.canvasX,d.canvasY,0,d.depth,d.mesh);this.baseZoomFactor=this.zoomFactor;this.mouseX=b;this.mouseY=c;break;case "release":if(this.onmouseup)this.onmouseup(d.canvasX,d.canvasY,0,d.depth,d.mesh);this.isTouchHeld=!1;break;case "hold":this.isTouchHeld=
!0;break;case "drag":if(this.onmousemove)this.onmousemove(d.canvasX,d.canvasY,0,d.depth,d.mesh);if(!this.isDefaultInputHandlerEnabled)break;this.isTouchHeld?(d="low"==this.definition?.5:"high"==this.definition?2:1,this.panning[0]+=d*(b-this.mouseX),this.panning[1]+=d*(c-this.mouseY)):(d=360*(b-this.mouseX)/this.canvas.height,this.rotMatrix.rotateAboutXAxis(360*(c-this.mouseY)/this.canvas.width),this.rotMatrix.rotateAboutYAxis(d));this.mouseX=b;this.mouseY=c;this.update();break;case "pinch":if(this.onmousewheel)this.onmousewheel(d.canvasX,
d.canvasY,0,d.depth,d.mesh);this.isDefaultInputHandlerEnabled&&(this.zoomFactor=this.baseZoomFactor*a.gesture.scale,this.update())}a.gesture.preventDefault();a.gesture.stopPropagation()}};
JSC3D.Viewer.prototype.loadScene=function(a){this.abortUnfinishedLoadingFn&&this.abortUnfinishedLoadingFn();this.scene=null;this.isLoaded=!1;this.update();if(""==this.sceneUrl)return!1;var b=this.sceneUrl.lastIndexOf("/");-1==b&&(b=this.sceneUrl.lastIndexOf("\\"));b=this.sceneUrl.substring(b+1);var c=b.lastIndexOf(".");if(-1==c)return!1;b=b.substring(c+1);var d=JSC3D.LoaderSelector.getLoader(b);if(!d)return!1;var e=this;d.onload=function(a){e.abortUnfinishedLoadingFn=null;e.setupScene(a);if(e.onloadingcomplete&&
"function"==typeof e.onloadingcomplete)e.onloadingcomplete()};d.onerror=function(a){e.scene=null;e.isLoaded=!1;e.isFailed=!0;e.abortUnfinishedLoadingFn=null;e.update();e.reportError(a);if(e.onloadingerror&&"function"==typeof e.onloadingerror)e.onloadingerror(a)};d.onprogress=function(a,b){e.showProgressBar&&e.reportProgress(a,b);if(e.onloadingprogress&&"function"==typeof e.onloadingprogress)e.onloadingprogress(a,b)};d.onresource=function(a){a instanceof JSC3D.Texture&&e.isMipMappingOn&&!a.hasMipmap()&&
a.generateMipmaps();e.update()};this.abortUnfinishedLoadingFn=function(){d.abort();e.abortUnfinishedLoadingFn=null;e.hideProgress();if(e.onloadingaborted&&"function"==typeof e.onloadingaborted)e.onloadingaborted()};d.loadFromUrl(this.sceneUrl,a);if(this.onloadingstarted&&"function"==typeof this.onloadingstarted)this.onloadingstarted();return!0};
JSC3D.Viewer.prototype.setupScene=function(a){if(0<=this.creaseAngle){var b=this.creaseAngle;a.forEachChild(function(a){a.creaseAngle=b})}a.init();if(!a.isEmpty()){var c=.7*a.aabb.lengthOfDiagonal(),d=this.frameWidth,e=this.frameHeight;this.zoomFactor=0==c?1:(d<e?d:e)/c;this.panning=[0,0]}this.rotMatrix.identity();this.rotMatrix.rotateAboutYAxis(this.initRotY);this.rotMatrix.rotateAboutXAxis(this.initRotX);this.rotMatrix.rotateAboutZAxis(this.initRotZ);this.scene=a;this.isLoaded=!0;this.needRepaint=
this.needUpdate=this.isFailed=!1;this.update();this.hideProgress();this.hideError()};
JSC3D.Viewer.prototype.reportProgress=function(a,b){if(!this.progressFrame){var c=this.canvas.getBoundingClientRect(),d="rgb("+(255-((this.bkgColor1&16711680)>>16))+","+(255-((this.bkgColor1&65280)>>8))+","+(255-(this.bkgColor1&255))+")",e=c.left+40,f=c.top+.38*c.height;c=c.width-2*(e-c.left);this.messagePanel||(this.messagePanel=document.createElement("div"),this.messagePanel.style.position="absolute",this.messagePanel.style.left=e+"px",this.messagePanel.style.top=f-16+"px",this.messagePanel.style.width=
c+"px",this.messagePanel.style.height="14px",this.messagePanel.style.font="bold 14px Courier New",this.messagePanel.style.color=d,this.messagePanel.style.pointerEvents="none",document.body.appendChild(this.messagePanel))}a&&"block"!=this.messagePanel.style.display&&(this.messagePanel.style.display="block");this.messagePanel.innerHTML=a};
JSC3D.Viewer.prototype.hideProgress=function(){this.progressFrame&&(this.messagePanel.style.display="none",this.progressFrame.style.display="none",this.progressRectangle.style.display="none")};
JSC3D.Viewer.prototype.reportError=function(a){if(!this.messagePanel){var b=this.canvas.getBoundingClientRect(),c="rgb("+(255-((this.bkgColor1&16711680)>>16))+","+(255-((this.bkgColor1&65280)>>8))+","+(255-(this.bkgColor1&255))+")",d=b.left+40,e=b.top+.38*b.height;b=b.width-2*(d-b.left);this.messagePanel=document.createElement("div");this.messagePanel.style.position="absolute";this.messagePanel.style.left=d+"px";this.messagePanel.style.top=e-16+"px";this.messagePanel.style.width=b+"px";this.messagePanel.style.height=
"14px";this.messagePanel.style.font="bold 14px Courier New";this.messagePanel.style.color=c;this.messagePanel.style.pointerEvents="none";document.body.appendChild(this.messagePanel)}a&&"block"!=this.messagePanel.style.display&&(this.messagePanel.style.display="block");this.messagePanel.innerHTML=a};JSC3D.Viewer.prototype.hideError=function(){this.messagePanel&&(this.messagePanel.style.display="none")};
JSC3D.Viewer.prototype.generateBackground=function(){this.webglBackend?this.bkgImage?this.webglBackend.setBackgroundImage(this.bkgImage):this.webglBackend.setBackgroundColors(this.bkgColor1,this.bkgColor2):this.bkgImage?this.fillBackgroundWithImage():this.fillGradientBackground()};
JSC3D.Viewer.prototype.fillGradientBackground=function(){for(var a=this.frameWidth,b=this.frameHeight,c=this.bkgColorBuffer,d=(this.bkgColor1&16711680)>>16,e=(this.bkgColor1&65280)>>8,f=this.bkgColor1&255,g=(this.bkgColor2&16711680)>>16,h=(this.bkgColor2&65280)>>8,k=this.bkgColor2&255,l=0,t=0;t<b;t++)for(var r=d+t*(g-d)/b&255,q=e+t*(h-e)/b&255,F=f+t*(k-f)/b&255,y=0;y<a;y++)c[l++]=r<<16|q<<8|F};
JSC3D.Viewer.prototype.fillBackgroundWithImage=function(){var a=this.frameWidth,b=this.frameHeight;if(!(0>=this.bkgImage.width||0>=this.bkgImage.height)){var c=!1,d=JSC3D.Texture.cv;if(!d)try{d=document.createElement("canvas"),JSC3D.Texture.cv=d,c=!0}catch(g){return}if(d.width!=a||d.height!=b)d.width=a,d.height=b,c=!0;var e=null;try{var f=d.getContext("2d");c||f.clearRect(0,0,a,b);f.drawImage(this.bkgImage,0,0,a,b);e=f.getImageData(0,0,a,b).data}catch(g){return}c=this.bkgColorBuffer;a*=b;for(d=b=
0;b<a;b++,d+=4)c[b]=e[d]<<16|e[d+1]<<8|e[d+2]}};JSC3D.Viewer.prototype.drawBackground=function(){if(this.webglBackend||this.ctx)this.beginScene(),this.endScene(),this.paint()};JSC3D.Viewer.prototype.beginScene=function(){if(this.webglBackend)this.webglBackend.beginFrame(this.definition);else for(var a=this.colorBuffer,b=this.zBuffer,c=this.selectionBuffer,d=this.bkgColorBuffer,e=this.frameWidth*this.frameHeight,f=-Number.MAX_VALUE,g=0;g<e;g++)a[g]=d[g],b[g]=f,c[g]=0};
JSC3D.Viewer.prototype.endScene=function(){if(this.webglBackend)this.webglBackend.endFrame();else{var a=this.canvasData.data,b=this.canvas.width,c=this.canvas.height,d=this.colorBuffer,e=this.frameWidth,f=e*this.frameHeight;switch(this.definition){case "low":var g=b>>1,h=e-g,k=0,l=0;for(f=0;f<c;f++){for(var t=0;t<b;t++)e=d[k],a[l]=(e&16711680)>>16,a[l+1]=(e&65280)>>8,a[l+2]=e&255,a[l+3]=255,k+=t&1,l+=4;k+=f&1?h:-g}break;case "high":for(f=l=k=0;f<c;f++){for(t=0;t<b;t++){g=d[k];h=d[k+1];var r=d[k+e],
q=d[k+e+1];a[l]=(g&16711680)+(h&16711680)+(r&16711680)+(q&16711680)>>18;a[l+1]=(g&65280)+(h&65280)+(r&65280)+(q&65280)>>10;a[l+2]=(g&255)+(h&255)+(r&255)+(q&255)>>2;a[l+3]=255;k+=2;l+=4}k+=e}break;default:for(l=k=0;k<f;k++,l+=4)e=d[k],a[l]=(e&16711680)>>16,a[l+1]=(e&65280)>>8,a[l+2]=e&255,a[l+3]=255}}};
JSC3D.Viewer.prototype.render=function(){if(!this.scene.isEmpty()){var a=this.scene.aabb;if(this.webglBackend){var b=this.frameWidth,c=this.frameHeight,d=a.lengthOfDiagonal(),e=b/c;this.transformMatrix.identity();this.transformMatrix.translate(-(a.minX+a.maxX)/2,-(a.minY+a.maxY)/2,-(a.minZ+a.maxZ)/2);this.transformMatrix.multiply(this.rotMatrix);b<c?this.transformMatrix.scale(2*this.zoomFactor/b,2*this.zoomFactor*e/b,-2/d):this.transformMatrix.scale(2*this.zoomFactor/(c*e),2*this.zoomFactor/c,-2/
d);this.transformMatrix.translate(2*this.panning[0]/b,-2*this.panning[1]/c,0)}else this.transformMatrix.identity(),this.transformMatrix.translate(-(a.minX+a.maxX)/2,-(a.minY+a.maxY)/2,-(a.minZ+a.maxZ)/2),this.transformMatrix.multiply(this.rotMatrix),this.transformMatrix.scale(this.zoomFactor,-this.zoomFactor,this.zoomFactor),this.transformMatrix.translate(this.frameWidth/2+this.panning[0],this.frameHeight/2+this.panning[1],0);a=this.sortScene(this.transformMatrix);if(this.webglBackend)this.webglBackend.render(this.scene.getChildren(),
this.transformMatrix,this.rotMatrix,this.renderMode,this.defaultMaterial,this.sphereMap);else for(b=0;b<a.length;b++)if(c=a[b],!c.isTrivial()&&(JSC3D.Math3D.transformVectors(this.transformMatrix,c.vertexBuffer,c.transformedVertexBuffer),c.visible))switch(c.renderMode||this.renderMode){case "point":this.renderPoint(c);break;case "wireframe":this.renderWireframe(c);break;case "flat":this.renderSolidFlat(c);break;case "smooth":this.renderSolidSmooth(c);break;case "texture":c.hasTexture()?this.renderSolidTexture(c):
this.renderSolidFlat(c);break;case "textureflat":c.hasTexture()?this.renderTextureFlat(c):this.renderSolidFlat(c);break;case "texturesmooth":c.isEnvironmentCast&&null!=this.sphereMap&&this.sphereMap.hasData()?this.renderSolidSphereMapped(c):c.hasTexture()?this.renderTextureSmooth(c):this.renderSolidSmooth(c);break;default:this.renderSolidFlat(c)}}};
JSC3D.Viewer.prototype.sortScene=function(a){for(var b=[],c=this.scene.getChildren(),d=0;d<c.length;d++){var e=c[d];if(!e.isTrivial()){b.push(e);var f=e.aabb.center();JSC3D.Math3D.transformVectors(a,f,f);e.sortKey={depth:f[2],isTransparnt:0<(e.material?e.material:this.defaultMaterial).transparency||(e.hasTexture()?e.texture.hasTransparency:!1)}}}b.sort(function(a,b){return!a.sortKey.isTransparnt&&b.sortKey.isTransparnt?-1:a.sortKey.isTransparnt&&!b.sortKey.isTransparnt?1:a.sortKey.isTransparnt?a.sortKey.depth-
b.sortKey.depth:b.sortKey.depth-a.sortKey.depth});return b};
JSC3D.Viewer.prototype.renderPoint=function(a){var b=this.frameWidth,c=b-1,d=this.frameHeight-1,e=a.transformedVertexBuffer,f=this.colorBuffer,g=this.zBuffer,h=this.selectionBuffer,k=e.length/3,l=a.internalId;a=a.material?a.material.diffuseColor:this.defaultMaterial.diffuseColor;for(var t=0,r=0;t<k;t++,r+=3){var q=~~(e[r]+.5),F=~~(e[r+1]+.5),y=e[r+2];0<=q&&q<c&&0<=F&&F<d&&(q=F*b+q,y>g[q]&&(g[q]=y,f[q]=a,h[q]=l),q++,y>g[q]&&(g[q]=y,f[q]=a,h[q]=l),q+=c,y>g[q]&&(g[q]=y,f[q]=a,h[q]=l),q++,y>g[q]&&(g[q]=
y,f[q]=a,h[q]=l))}};
JSC3D.Viewer.prototype.renderWireframe=function(a){var b=this.frameWidth,c=b-1,d=this.frameHeight-1,e=a.indexBuffer,f=a.transformedVertexBuffer,g=a.transformedFaceNormalZBuffer,h=this.colorBuffer,k=this.zBuffer,l=this.selectionBuffer,t=a.faceCount,r=a.internalId,q=a.material?a.material.diffuseColor:this.defaultMaterial.diffuseColor;if(!g||g.length<t)a.transformedFaceNormalZBuffer=Array(t),g=a.transformedFaceNormalZBuffer;JSC3D.Math3D.transformVectorZs(this.rotMatrix,a.faceNormalBuffer,g);for(var F=
0,y=0;F<t;){var O=g[F++];a.isDoubleSided&&(O=0<O?O:-O);if(0>O)for(;-1!=e[y++];);else{var C=3*e[y++];var p=3*e[y++];O=C;for(var z=!1;!z;){var Q=~~(f[C]+.5),I=~~(f[C+1]+.5),B=f[C+2],L=~~(f[p]+.5),A=~~(f[p+1]+.5),n=f[p+2],m=L-Q,u=A-I,D=n-B;if(Math.abs(m)>Math.abs(u)){var x=m;var M=0<m?1:-1;var E=0!=m?M*u/m:0;var R=0!=m?M*D/m:0}else x=u,E=0<u?1:-1,M=0!=u?E*m/u:0,R=0!=u?E*D/u:0;0>x&&(Q=L,I=A,B=n,x=-x,M=-M,E=-E,R=-R);L=a.material.lijnDikte?.5*a.material.lijnDikte:.5;D=10;for(A=0;A<x;A++){if(0<=Q&&Q<c&&
0<=I&&I<d){u=0;for(m=-L;m<=L;m++){var G=m,P=u;n=D;G=~~(I+P)*b+~~(Q+G);B+n>k[G]&&(k[G]=B+n,h[G]=q,l[G]=r)}m=0;for(u=-L;u<=L;u++)G=m,P=u,n=D,G=~~(I+P)*b+~~(Q+G),B+n>k[G]&&(k[G]=B+n,h[G]=q,l[G]=r)}Q+=M;I+=E;B+=R}p==O?z=!0:(C=p,p=-1!=e[y]?3*e[y++]:O)}y++}}};
JSC3D.Viewer.prototype.renderSolidFlat=function(a){var b=this.frameWidth,c=this.frameHeight,d=a.indexBuffer,e=a.transformedVertexBuffer,f=a.transformedFaceNormalZBuffer,g=this.colorBuffer,h=this.zBuffer,k=this.selectionBuffer,l=a.faceCount,t=a.internalId,r=a.material?a.material:this.defaultMaterial,q=r.getPalette(),F=0==r.transparency,y=255*r.transparency,O=255-y;if(1!=r.transparency){if(!f||f.length<l)a.transformedFaceNormalZBuffer=Array(l),f=a.transformedFaceNormalZBuffer;JSC3D.Math3D.transformVectorZs(this.rotMatrix,
a.faceNormalBuffer,f);for(var C=Array(3),p=Array(3),z=Array(3),Q=0,I=0;Q<l;){var B=f[Q++];a.isDoubleSided&&(B=0<B?B:-B);if(0>B)for(;-1!=d[I++];);else{var L=a.material.shadow?a.material.shadow/100:1;B=1-L+L*B;L=q[~~(255*B)];if(r.usePalettes&&r.palettes&&r.map_face_form){var A=r.map_face_form[Q-1];r.palettes[A]&&(L=r.palettes[A][~~(255*B)])}B=3*d[I++];var n=3*d[I++];do{A=3*d[I++];C[0]=~~(e[B]+.5);p[0]=~~(e[B+1]+.5);z[0]=e[B+2];C[1]=~~(e[n]+.5);p[1]=~~(e[n+1]+.5);z[1]=e[n+2];C[2]=~~(e[A]+.5);p[2]=~~(e[A+
1]+.5);z[2]=e[A+2];n=p[0]<p[1]?0:1;n=p[n]<p[2]?n:2;var m=p[0]>p[1]?0:1;m=p[m]>p[2]?m:2;var u=3-m-n;if(n!=m){var D=C[m],x=z[m],M=p[m]-p[n];M=0!=M?M:1;var E=(C[m]-C[n])/M;M=(z[m]-z[n])/M;var R=C[m],G=z[m],P=p[m]-p[u];P=0!=P?P:1;var ia=(C[m]-C[u])/P;P=(z[m]-z[u])/P;var ba=C[u],ca=z[u],T=p[u]-p[n];T=0!=T?T:1;var H=(C[u]-C[n])/T;T=(z[u]-z[n])/T;var v=p[m]*b;for(m=p[m];m>p[n];m--){if(0<=m&&m<c){var w=~~D,U=x;if(m>p[u]){var S=~~R;var W=G}else S=~~ba,W=ca;if(w>S){var J=w;w=S;S=J;J=U;U=W;W=J}0>w&&(w=0);S>=
b&&(S=b-1);W=w!=S?(W-U)/(S-w):1;J=v+w;if(F)for(;w<=S;w++,U+=W)U>h[J]&&(h[J]=U,g[J]=L,k[J]=t),J++;else for(;w<S;w++,U+=W){if(U>h[J]){h[J]=U;var ja=L,V=g[J];g[J]=(V&16711680)*y+(ja&16711680)*O>>8&16711680|(V&65280)*y+(ja&65280)*O>>8&65280|(V&255)*y+(ja&255)*O>>8&255;k[J]=t}J++}}D-=E;x-=M;m>p[u]?(R-=ia,G-=P):(ba-=H,ca-=T);v-=b}}n=A}while(-1!=d[I]);I++}}}};
JSC3D.Viewer.prototype.renderSolidSphereMapped=function(a){var b=this.frameWidth,c=this.frameHeight,d=a.indexBuffer,e=a.transformedVertexBuffer,f=a.transformedVertexNormalBuffer,g=a.vertexNormalIndexBuffer?a.vertexNormalIndexBuffer:a.indexBuffer,h=a.transformedFaceNormalZBuffer,k=this.colorBuffer,l=this.zBuffer,t=this.selectionBuffer,r=a.faceCount,q=a.internalId,F=a.material?a.material:this.defaultMaterial,y=F.getPalette(),O=this.sphereMap,C=O.data,p=O.width,z=p-1,Q=0==F.transparency,I=255*F.transparency,
B=255-I;if(1!=F.transparency){if(!f||f.length<a.vertexNormalBuffer.length)a.transformedVertexNormalBuffer=Array(a.vertexNormalBuffer.length),f=a.transformedVertexNormalBuffer;if(!h||h.length<r)a.transformedFaceNormalZBuffer=Array(r),h=a.transformedFaceNormalZBuffer;JSC3D.Math3D.transformVectors(this.rotMatrix,a.vertexNormalBuffer,f);JSC3D.Math3D.transformVectorZs(this.rotMatrix,a.faceNormalBuffer,h);for(var L=a.isDoubleSided,A=Array(3),n=Array(3),m=Array(3),u=Array(3),D=Array(3),x=Array(3),M=0,E=
0;M<r;){var R=h[M++];L&&(R=0<R?R:-R);if(0>R)for(;-1!=d[E++];);else{var G=3*d[E];var P=3*g[E];E++;var ia=3*d[E];var ba=3*g[E];E++;do{var ca=3*d[E];var T=3*g[E];E++;A[0]=~~(e[G]+.5);n[0]=~~(e[G+1]+.5);m[0]=e[G+2];A[1]=~~(e[ia]+.5);n[1]=~~(e[ia+1]+.5);m[1]=e[ia+2];A[2]=~~(e[ca]+.5);n[2]=~~(e[ca+1]+.5);m[2]=e[ca+2];u[0]=f[P];D[0]=f[P+1];x[0]=f[P+2];u[1]=f[ba];D[1]=f[ba+1];x[1]=f[ba+2];u[2]=f[T];D[2]=f[T+1];x[2]=f[T+2];L&&(0>x[0]&&(x[0]=-x[0]),0>x[1]&&(x[1]=-x[1]),0>x[2]&&(x[2]=-x[2]));var H=n[0]<n[1]?
0:1;H=n[H]<n[2]?H:2;var v=n[0]>n[1]?0:1;v=n[v]>n[2]?v:2;var w=3-v-H;if(H!=v){var U=A[v],S=m[v],W=255*x[v],J=(u[v]/2+.5)*p&z,ja=(.5-D[v]/2)*p&z,V=n[v]-n[H];V=0!=V?V:1;var Qa=(A[v]-A[H])/V,Ra=(m[v]-m[H])/V,Sa=255*(x[v]-x[H])/V,Ta=(u[v]-u[H])/2*p/V,Ua=(D[H]-D[v])/2*p/V,Fa=A[v],Ga=m[v],Ha=255*x[v],Ia=(u[v]/2+.5)*p&z,Ja=(.5-D[v]/2)*p&z,Z=n[v]-n[w];Z=0!=Z?Z:1;var Va=(A[v]-A[w])/Z,Wa=(m[v]-m[w])/Z,Xa=255*(x[v]-x[w])/Z,Ya=(u[v]-u[w])/2*p/Z,Za=(D[w]-D[v])/2*p/Z,Ka=A[w],La=m[w],Ma=255*x[w],Na=(u[w]/2+.5)*p&
z,Oa=(.5-D[w]/2)*p&z,aa=n[w]-n[H];aa=0!=aa?aa:1;for(var $a=(A[w]-A[H])/aa,ab=(m[w]-m[H])/aa,bb=255*(x[w]-x[H])/aa,cb=(u[w]-u[H])/2*p/aa,db=(D[H]-D[w])/2*p/aa,Pa=n[v]*b,ka=n[v];ka>n[H];ka--){if(0<=ka&&ka<c){var K=~~U,la=S,ma=W,da=J,ea=ja;if(ka>n[w]){var N=~~Fa;var ua=Ga;var va=Ha;var wa=Ia;var xa=Ja}else N=~~Ka,ua=La,va=Ma,wa=Na,xa=Oa;if(K>N){var Y=K;K=N;N=Y;Y=la;la=ua;ua=Y;Y=ma;ma=va;va=Y;Y=da;da=wa;wa=Y;Y=ea;ea=xa;xa=Y}var ya=K!=N?(ua-la)/(N-K):1,za=K!=N?(va-ma)/(N-K):1,Aa=K!=N?(wa-da)/(N-K):1,Ba=
K!=N?(xa-ea)/(N-K):1;0>K&&(la-=K*ya,ma-=K*za,da-=da*Aa,ea-=ea*Ba,K=0);N>=b&&(N=b-1);var X=Pa+K;if(Q)for(var oa=K,na=la,fa=ma,pa=da,qa=ea;oa<=N;oa++,na+=ya,fa+=za,pa+=Aa,qa+=Ba){if(na>l[X]){l[X]=na;var ha=y[0<fa?~~fa:0],Ca=C[(qa&z)*p+(pa&z)],ra=((ha&16711680)>>16)*((Ca&16711680)>>8),sa=((ha&65280)>>8)*((Ca&65280)>>8),ta=(ha&255)*(Ca&255)>>8;k[X]=ra&16711680|sa&65280|ta&255;t[X]=q}X++}else for(oa=K,na=la,fa=ma,pa=da,qa=ea;oa<N;oa++,na+=ya,fa+=za,pa+=Aa,qa+=Ba){if(na>l[X]){ha=y[0<fa?~~fa:0];var Da=C[(qa&
z)*p+(pa&z)],Ea=k[X];ra=((ha&16711680)>>16)*((Da&16711680)>>8);sa=((ha&65280)>>8)*((Da&65280)>>8);ta=(ha&255)*(Da&255)>>8;ra=ra*B+(Ea&16711680)*I>>8;sa=sa*B+(Ea&65280)*I>>8;ta=ta*B+(Ea&255)*I>>8;k[X]=ra&16711680|sa&65280|ta&255;t[X]=q}X++}}U-=Qa;S-=Ra;W-=Sa;J-=Ta;ja-=Ua;ka>n[w]?(Fa-=Va,Ga-=Wa,Ha-=Xa,Ia-=Ya,Ja-=Za):(Ka-=$a,La-=ab,Ma-=bb,Na-=cb,Oa-=db);Pa-=b}}ia=ca;ba=T}while(-1!=d[E]);E++}}}};JSC3D.Viewer.prototype.params=null;JSC3D.Viewer.prototype.canvas=null;JSC3D.Viewer.prototype.ctx=null;
JSC3D.Viewer.prototype.canvasData=null;JSC3D.Viewer.prototype.bkgColorBuffer=null;JSC3D.Viewer.prototype.colorBuffer=null;JSC3D.Viewer.prototype.zBuffer=null;JSC3D.Viewer.prototype.selectionBuffer=null;JSC3D.Viewer.prototype.frameWidth=0;JSC3D.Viewer.prototype.frameHeight=0;JSC3D.Viewer.prototype.scene=null;JSC3D.Viewer.prototype.defaultMaterial=null;JSC3D.Viewer.prototype.sphereMap=null;JSC3D.Viewer.prototype.isLoaded=!1;JSC3D.Viewer.prototype.isFailed=!1;JSC3D.Viewer.prototype.needUpdate=!1;
JSC3D.Viewer.prototype.needRepaint=!1;JSC3D.Viewer.prototype.initRotX=0;JSC3D.Viewer.prototype.initRotY=0;JSC3D.Viewer.prototype.initRotZ=0;JSC3D.Viewer.prototype.zoomFactor=1;JSC3D.Viewer.prototype.panning=[0,0];JSC3D.Viewer.prototype.rotMatrix=null;JSC3D.Viewer.prototype.transformMatrix=null;JSC3D.Viewer.prototype.sceneUrl="";JSC3D.Viewer.prototype.modelColor=13280792;JSC3D.Viewer.prototype.bkgColor1=16777215;JSC3D.Viewer.prototype.bkgColor2=16777088;JSC3D.Viewer.prototype.renderMode="flat";
JSC3D.Viewer.prototype.definition="standard";JSC3D.Viewer.prototype.isMipMappingOn=!1;JSC3D.Viewer.prototype.creaseAngle=-180;JSC3D.Viewer.prototype.sphereMapUrl="";JSC3D.Viewer.prototype.showProgressBar=!0;JSC3D.Viewer.prototype.buttonStates=null;JSC3D.Viewer.prototype.keyStates=null;JSC3D.Viewer.prototype.mouseX=0;JSC3D.Viewer.prototype.mouseY=0;JSC3D.Viewer.prototype.onloadingstarted=null;JSC3D.Viewer.prototype.onloadingcomplete=null;JSC3D.Viewer.prototype.onloadingprogress=null;
JSC3D.Viewer.prototype.onloadingaborted=null;JSC3D.Viewer.prototype.onloadingerror=null;JSC3D.Viewer.prototype.onmousedown=null;JSC3D.Viewer.prototype.onmouseup=null;JSC3D.Viewer.prototype.onmousemove=null;JSC3D.Viewer.prototype.onmousewheel=null;JSC3D.Viewer.prototype.beforeupdate=null;JSC3D.Viewer.prototype.afterupdate=null;JSC3D.Viewer.prototype.mouseUsage="default";JSC3D.Viewer.prototype.isDefaultInputHandlerEnabled=!1;
JSC3D.PickInfo=function(){this.canvasY=this.canvasX=0;this.depth=-Infinity;this.mesh=null};JSC3D.Scene=function(a){this.name=a||"";this.aabb=null;this.children=[];this.maxChildId=1};JSC3D.Scene.prototype.init=function(){if(!this.isEmpty()){for(var a=0;a<this.children.length;a++)this.children[a].init();this.aabb||(this.aabb=new JSC3D.AABB,this.calcAABB())}};JSC3D.Scene.prototype.isEmpty=function(){return 0==this.children.length};
JSC3D.Scene.prototype.addChild=function(a){a.internalId=this.maxChildId++;this.children.push(a)};JSC3D.Scene.prototype.removeChild=function(a){a=this.children.indexOf(a);0<=a&&this.children.splice(a,1)};JSC3D.Scene.prototype.getChildren=function(){return this.children.slice(0)};JSC3D.Scene.prototype.getChild=function(a){return this.children[a]};JSC3D.Scene.prototype.forEachChild=function(a){if("function"==typeof a)for(var b=0;b<this.children.length&&!a.call(null,this.children[b]);b++);};
JSC3D.Scene.prototype.calcAABB=function(){this.aabb.minX=this.aabb.minY=this.aabb.minZ=Number.MAX_VALUE;this.aabb.maxX=this.aabb.maxY=this.aabb.maxZ=-Number.MAX_VALUE;for(var a=0;a<this.children.length;a++){var b=this.children[a];if(!b.isTrivial()){var c=b.aabb.minX,d=b.aabb.minY,e=b.aabb.minZ,f=b.aabb.maxX,g=b.aabb.maxY;b=b.aabb.maxZ;this.aabb.minX>c&&(this.aabb.minX=c);this.aabb.minY>d&&(this.aabb.minY=d);this.aabb.minZ>e&&(this.aabb.minZ=e);this.aabb.maxX<f&&(this.aabb.maxX=f);this.aabb.maxY<g&&
(this.aabb.maxY=g);this.aabb.maxZ<b&&(this.aabb.maxZ=b)}}};JSC3D.Scene.prototype.name="";JSC3D.Scene.prototype.aabb=null;JSC3D.Scene.prototype.children=null;JSC3D.Scene.prototype.maxChildId=1;
JSC3D.Mesh=function(a,b,c,d,e,f,g,h,k,l,t){this.name=a||"";this.metadata="";this.visible=void 0!=b?b:!0;this.aabb=this.renderMode=null;this.vertexBuffer=h||null;this.indexBuffer=k||null;this.faceNormalBuffer=this.vertexNormalIndexBuffer=this.vertexNormalBuffer=null;this.material=c||null;this.texture=d||null;this.faceCount=0;this.creaseAngle=0<=e?e:-180;this.isDoubleSided=f||!1;this.isEnvironmentCast=g||!1;this.internalId=0;this.texCoordBuffer=l||null;this.texCoordIndexBuffer=t||null;this.transformedVertexNormalBuffer=
this.transformedFaceNormalZBuffer=this.transformedVertexNormalZBuffer=this.transformedVertexBuffer=null;this.renderMode="flat";this.palettes=null};
JSC3D.Mesh.prototype.init=function(){if(!this.isTrivial()){if(0==this.faceCount&&(this.calcFaceCount(),0==this.faceCount))return;this.aabb||(this.aabb=new JSC3D.AABB,this.calcAABB());this.faceNormalBuffer||(this.faceNormalBuffer=Array(3*this.faceCount),this.calcFaceNormals());this.vertexNormalBuffer||(0<=this.creaseAngle?this.calcCreasedVertexNormals():(this.vertexNormalBuffer=Array(this.vertexBuffer.length),this.calcVertexNormals()));this.normalizeFaceNormals();this.transformedVertexBuffer=Array(this.vertexBuffer.length)}};
JSC3D.Mesh.prototype.isTrivial=function(){return!this.vertexBuffer||3>this.vertexBuffer.length||!this.indexBuffer||3>this.indexBuffer.length};JSC3D.Mesh.prototype.setMaterial=function(a){this.material=a};JSC3D.Mesh.prototype.setTexture=function(a){this.texture=a};
JSC3D.Mesh.prototype.hasTexture=function(){return null!=this.texture&&this.texture.hasData()&&null!=this.texCoordBuffer&&2<=this.texCoordBuffer.length&&(null==this.texCoordIndexBuffer||3<=this.texCoordIndexBuffer.length&&this.texCoordIndexBuffer.length>=this.indexBuffer.length)};JSC3D.Mesh.prototype.setRenderMode=function(a){this.renderMode=a};JSC3D.Mesh.prototype.calcFaceCount=function(){this.faceCount=0;var a=this.indexBuffer;-1!=a[a.length-1]&&a.push(-1);for(var b=0;b<a.length;b++)-1==a[b]&&this.faceCount++};
JSC3D.Mesh.prototype.calcAABB=function(){for(var a=minY=minZ=Number.MAX_VALUE,b=maxY=maxZ=-Number.MAX_VALUE,c=this.vertexBuffer,d=0;d<c.length;d+=3){var e=c[d],f=c[d+1],g=c[d+2];e<a&&(a=e);e>b&&(b=e);f<minY&&(minY=f);f>maxY&&(maxY=f);g<minZ&&(minZ=g);g>maxZ&&(maxZ=g)}this.aabb.minX=a;this.aabb.minY=minY;this.aabb.minZ=minZ;this.aabb.maxX=b;this.aabb.maxY=maxY;this.aabb.maxZ=maxZ};
JSC3D.Mesh.prototype.calcFaceNormals=function(){for(var a=this.vertexBuffer,b=this.indexBuffer,c=this.faceNormalBuffer,d=0,e=0;d<b.length;){var f=3*b[d++],g=a[f],h=a[f+1],k=a[f+2];f=3*b[d++];var l=a[f],t=a[f+1],r=a[f+2];f=3*b[d++];l-=g;t-=h;r-=k;g=a[f]-g;h=a[f+1]-h;k=a[f+2]-k;f=t*k-r*h;k=r*g-l*k;l=l*h-t*g;c[e++]=f;c[e++]=k;for(c[e++]=l;-1!=b[d++];);}};JSC3D.Mesh.prototype.normalizeFaceNormals=function(){JSC3D.Math3D.normalizeVectors(this.faceNormalBuffer,this.faceNormalBuffer)};
JSC3D.Mesh.prototype.calcVertexNormals=function(){this.faceNormalBuffer||(this.faceNormalBuffer=Array(3*this.faceCount),this.calcFaceNormals());for(var a=this.indexBuffer,b=this.faceNormalBuffer,c=this.vertexNormalBuffer,d=0;d<c.length;d++)c[d]=0;this.vertexNormalIndexBuffer=null;for(var e=d=0,f;d<a.length;)f=a[d++],-1==f?e+=3:(f*=3,c[f]+=b[e],c[f+1]+=b[e+1],c[f+2]+=b[e+2]);JSC3D.Math3D.normalizeVectors(c,c)};
JSC3D.Mesh.prototype.normalizeFaceNormals=function(){for(var a=this.faceNormalBuffer,b=0;b<a.length;b+=3){var c=a[b],d=a[b+1],e=a[b+2],f=Math.sqrt(c*c+d*d+e*e);0<f&&(c/=f,d/=f,e/=f);a[b]=c;a[b+1]=d;a[b+2]=e}};JSC3D.Mesh.prototype.checkValid=function(){};JSC3D.Mesh.prototype.name="";JSC3D.Mesh.prototype.metadata="";JSC3D.Mesh.prototype.visible=!1;JSC3D.Mesh.prototype.renderMode="flat";JSC3D.Mesh.prototype.aabb=null;JSC3D.Mesh.prototype.vertexBuffer=null;JSC3D.Mesh.prototype.indexBuffer=null;
JSC3D.Mesh.prototype.vertexNormalBuffer=null;JSC3D.Mesh.prototype.vertexNormalIndexBuffer=null;JSC3D.Mesh.prototype.faceNormalBuffer=null;JSC3D.Mesh.prototype.texCoordBuffer=null;JSC3D.Mesh.prototype.texCoordIndexBuffer=null;JSC3D.Mesh.prototype.material=null;JSC3D.Mesh.prototype.texture=null;JSC3D.Mesh.prototype.faceCount=0;JSC3D.Mesh.prototype.creaseAngle=-180;JSC3D.Mesh.prototype.isDoubleSided=!1;JSC3D.Mesh.prototype.isEnvironmentCast=!1;JSC3D.Mesh.prototype.internalId=0;
JSC3D.Mesh.prototype.transformedVertexBuffer=null;JSC3D.Mesh.prototype.transformedVertexNormalZBuffer=null;JSC3D.Mesh.prototype.transformedFaceNormalZBuffer=null;JSC3D.Mesh.prototype.transformedVertexNormalBuffer=null;JSC3D.Mesh.prototype.renderMode="flat";JSC3D.Mesh.prototype.palettes=null;JSC3D.Material=function(a,b,c,d,e){this.name=a||"";this.ambientColor=b||0;this.diffuseColor=c||8355711;this.transparency=d||0;this.simulateSpecular=e||!1;this.palette=null;this.usePalettes=!1};
JSC3D.Material.prototype.getPalette=function(){this.palette||(this.palette=Array(256),this.generatePalette());return this.palette};
JSC3D.Material.prototype.generatePalette=function(){var a=(this.ambientColor&16711680)>>16,b=(this.ambientColor&65280)>>8,c=this.ambientColor&255,d=(this.diffuseColor&16711680)>>16,e=(this.diffuseColor&65280)>>8,f=this.diffuseColor&255;if(this.simulateSpecular){for(var g=0;204>g;){var h=a+g*d/204,k=b+g*e/204,l=c+g*f/204;255<h&&(h=255);255<k&&(k=255);255<l&&(l=255);this.palette[g++]=h<<16|k<<8|l}for(;256>g;)h=a+d+(g-204)*(255-d)/82,k=b+e+(g-204)*(255-e)/82,l=c+f+(g-204)*(255-f)/82,255<h&&(h=255),255<
k&&(k=255),255<l&&(l=255),this.palette[g++]=h<<16|k<<8|l}else for(g=0;256>g;)h=a+g*d/256,k=b+g*e/256,l=c+g*f/256,255<h&&(h=255),255<k&&(k=255),255<l&&(l=255),this.palette[g++]=h<<16|k<<8|l};JSC3D.Material.prototype.name="";JSC3D.Material.prototype.ambientColor=0;JSC3D.Material.prototype.diffuseColor=8355711;JSC3D.Material.prototype.transparency=0;JSC3D.Material.prototype.simulateSpecular=!1;JSC3D.Material.prototype.palette=null;JSC3D.Material.prototype.palettes=null;
JSC3D.Material.prototype.map_face_form=null;JSC3D.Texture=function(a,b){this.name=a||"";this.height=this.width=0;this.mipentries=this.mipmaps=this.data=null;this.hasTransparency=!1;this.srcUrl="";this.onready=b&&"function"==typeof b?b:null};
JSC3D.Texture.prototype.createFromUrl=function(a,b){var c=this,d=new Image;d.onload=function(){c.data=null;c.mipmaps=null;c.mipentries=null;c.width=0;c.height=0;c.hasTransparency=!1;c.srcUrl="";c.createFromImage(this,b);JSC3D.console&&JSC3D.console.logInfo('Finished loading texture image file "'+this.src+'".')};d.onerror=function(){c.data=null;c.mipmaps=null;c.mipentries=null;c.width=0;c.height=0;c.hasTransparency=!1;c.srcUrl="";JSC3D.console&&JSC3D.console.logWarning('Failed to load texture image file "'+
this.src+'". This texture will be discarded.')};d.src=a};
JSC3D.Texture.prototype.createFromImage=function(a,b){if(!(0>=a.width||0>=a.height)){var c=!1,d=JSC3D.Texture.cv;if(!d)try{d=document.createElement("canvas"),JSC3D.Texture.cv=d,c=!0}catch(k){return}var e=a.width>a.height?a.width:a.height;e=32>=e?32:64>=e?64:128>=e?128:256>=e?256:512>=e?512:1024;if(d.width!=e||d.height!=e)d.width=d.height=e,c=!0;try{var f=d.getContext("2d");c||f.clearRect(0,0,e,e);f.drawImage(a,0,0,e,e);var g=f.getImageData(0,0,e,e).data}catch(k){return}c=g.length/4;this.data=Array(c);
for(var h=f=0;f<c;f++,h+=4)d=g[h+3],this.data[f]=d<<24|g[h]<<16|g[h+1]<<8|g[h+2],255>d&&(this.hasTransparency=!0);this.height=this.width=e;this.mipmaps=null;b&&this.generateMipmaps();this.srcUrl=a.src;if(null!=this.onready&&"function"==typeof this.onready)this.onready()}};JSC3D.Texture.prototype.hasData=function(){return null!=this.data};
JSC3D.Texture.prototype.generateMipmaps=function(){if(!(1>=this.width||null==this.data||null!=this.mipmaps)){this.mipmaps=[this.data];this.mipentries=[1];for(var a=1+~~(.1+Math.log(this.width)*Math.LOG2E),b=this.width>>1,c=1;c<a;c++){for(var d=Array(b*b),e=this.mipmaps[c-1],f=b<<1,g=0,h=0,k=0;k<b;k++){for(var l=0;l<b;l++){var t=e[g],r=e[g+1],q=e[g+f],F=e[g+f+1];d[h]=(((t&4278190080)>>>2)+((r&4278190080)>>>2)+((q&4278190080)>>>2)+((F&4278190080)>>>2)&4278190080)+((t&16711680)+(r&16711680)+(q&16711680)+
(F&16711680)>>2&16711680)+((t&65280)+(r&65280)+(q&65280)+(F&65280)>>2&65280)+((t&255)+(r&255)+(q&255)+(F&255)>>2&255);g+=2;h++}g+=f}this.mipmaps.push(d);this.mipentries.push(Math.pow(4,c));b>>=1}}};JSC3D.Texture.prototype.hasMipmap=function(){return null!=this.mipmaps};JSC3D.Texture.prototype.name="";JSC3D.Texture.prototype.data=null;JSC3D.Texture.prototype.mipmaps=null;JSC3D.Texture.prototype.mipentries=null;JSC3D.Texture.prototype.width=0;JSC3D.Texture.prototype.height=0;
JSC3D.Texture.prototype.hasTransparency=!1;JSC3D.Texture.prototype.srcUrl="";JSC3D.Texture.prototype.onready=null;JSC3D.Texture.cv=null;JSC3D.AABB=function(){this.minZ=this.maxZ=this.minY=this.maxY=this.minX=this.maxX=0};JSC3D.AABB.prototype.center=function(){return[(this.minX+this.maxX)/2,(this.minY+this.maxY)/2,(this.minZ+this.maxZ)/2]};JSC3D.AABB.prototype.lengthOfDiagonal=function(){var a=this.maxX-this.minX,b=this.maxY-this.minY,c=this.maxZ-this.minZ;return Math.sqrt(a*a+b*b+c*c)};
JSC3D.Matrix3x4=function(){this.m00=1;this.m10=this.m03=this.m02=this.m01=0;this.m11=1;this.m21=this.m20=this.m13=this.m12=0;this.m22=1;this.m23=0};JSC3D.Matrix3x4.prototype.identity=function(){this.m00=1;this.m10=this.m03=this.m02=this.m01=0;this.m11=1;this.m21=this.m20=this.m13=this.m12=0;this.m22=1;this.m23=0};
JSC3D.Matrix3x4.prototype.scale=function(a,b,c){this.m00*=a;this.m01*=a;this.m02*=a;this.m03*=a;this.m10*=b;this.m11*=b;this.m12*=b;this.m13*=b;this.m20*=c;this.m21*=c;this.m22*=c;this.m23*=c};JSC3D.Matrix3x4.prototype.translate=function(a,b,c){this.m03+=a;this.m13+=b;this.m23+=c};
JSC3D.Matrix3x4.prototype.rotateAboutXAxis=function(a){if(0!=a){a*=Math.PI/180;var b=Math.cos(a);a=Math.sin(a);var c=b*this.m11-a*this.m21,d=b*this.m12-a*this.m22,e=b*this.m13-a*this.m23,f=b*this.m20+a*this.m10,g=b*this.m21+a*this.m11,h=b*this.m22+a*this.m12,k=b*this.m23+a*this.m13;this.m10=b*this.m10-a*this.m20;this.m11=c;this.m12=d;this.m13=e;this.m20=f;this.m21=g;this.m22=h;this.m23=k}};
JSC3D.Matrix3x4.prototype.rotateAboutYAxis=function(a){if(0!=a){a*=Math.PI/180;var b=Math.cos(a);a=Math.sin(a);var c=b*this.m01+a*this.m21,d=b*this.m02+a*this.m22,e=b*this.m03+a*this.m23,f=b*this.m20-a*this.m00,g=b*this.m21-a*this.m01,h=b*this.m22-a*this.m02,k=b*this.m23-a*this.m03;this.m00=b*this.m00+a*this.m20;this.m01=c;this.m02=d;this.m03=e;this.m20=f;this.m21=g;this.m22=h;this.m23=k}};
JSC3D.Matrix3x4.prototype.rotateAboutZAxis=function(a){if(0!=a){a*=Math.PI/180;var b=Math.cos(a);a=Math.sin(a);var c=b*this.m10+a*this.m00,d=b*this.m11+a*this.m01,e=b*this.m12+a*this.m02,f=b*this.m13+a*this.m03,g=b*this.m01-a*this.m11,h=b*this.m02-a*this.m12,k=b*this.m03-a*this.m13;this.m00=b*this.m00-a*this.m10;this.m01=g;this.m02=h;this.m03=k;this.m10=c;this.m11=d;this.m12=e;this.m13=f}};
JSC3D.Matrix3x4.prototype.multiply=function(a){var b=a.m00*this.m01+a.m01*this.m11+a.m02*this.m21,c=a.m00*this.m02+a.m01*this.m12+a.m02*this.m22,d=a.m00*this.m03+a.m01*this.m13+a.m02*this.m23+a.m03,e=a.m10*this.m00+a.m11*this.m10+a.m12*this.m20,f=a.m10*this.m01+a.m11*this.m11+a.m12*this.m21,g=a.m10*this.m02+a.m11*this.m12+a.m12*this.m22,h=a.m10*this.m03+a.m11*this.m13+a.m12*this.m23+a.m13,k=a.m20*this.m00+a.m21*this.m10+a.m22*this.m20,l=a.m20*this.m01+a.m21*this.m11+a.m22*this.m21,t=a.m20*this.m02+
a.m21*this.m12+a.m22*this.m22,r=a.m20*this.m03+a.m21*this.m13+a.m22*this.m23+a.m23;this.m00=a.m00*this.m00+a.m01*this.m10+a.m02*this.m20;this.m01=b;this.m02=c;this.m03=d;this.m10=e;this.m11=f;this.m12=g;this.m13=h;this.m20=k;this.m21=l;this.m22=t;this.m23=r};JSC3D.Matrix3x4.prototype.getCopy=function(){copy=new JSC3D.Matrix3x4;copy.m00=this.m00;copy.m01=this.m01;copy.m02=this.m02;copy.m10=this.m10;copy.m11=this.m11;copy.m12=this.m12;copy.m20=this.m20;copy.m21=this.m21;copy.m22=this.m22;return copy};
JSC3D.Math3D={transformVectors:function(a,b,c){for(var d=0;d<b.length;d+=3){var e=b[d],f=b[d+1],g=b[d+2];c[d]=a.m00*e+a.m01*f+a.m02*g+a.m03;c[d+1]=a.m10*e+a.m11*f+a.m12*g+a.m13;c[d+2]=a.m20*e+a.m21*f+a.m22*g+a.m23}},transformVectorZs:function(a,b,c){for(var d=b.length/3,e=0,f=0;e<d;)c[e]=a.m20*b[f]+a.m21*b[f+1]+a.m22*b[f+2]+a.m23,e++,f+=3},normalizeVectors:function(a,b){for(var c=a.length,d=0;d<c;d+=3){var e=a[d],f=a[d+1],g=a[d+2],h=Math.sqrt(e*e+f*f+g*g);0<h&&(h=1/h,e*=h,f*=h,g*=h);b[d]=e;b[d+1]=
f;b[d+2]=g}}};
JSC3D.PlatformInfo=function(){for(var a={browser:"other",version:"n/a",isTouchDevice:void 0!=document.createTouch,supportTypedArrays:void 0!=window.Uint32Array,supportWebGL:void 0!=window.WebGLRenderingContext},b=[["firefox",/Firefox[\/\s](\d+(?:\.\d+)*)/],["chrome",/Chrome[\/\s](\d+(?:\.\d+)*)/],["opera",/Opera[\/\s](\d+(?:\.\d+)*)/],["safari",/Safari[\/\s](\d+(?:\.\d+)*)/],["webkit",/AppleWebKit[\/\s](\d+(?:\.\d+)*)/],["ie",/MSIE[\/\s](\d+(?:\.\d+)*)/],["ie",/Trident\/\d+\.\d+;\s.*rv:(\d+(?:\.\d+)*)/]],c,
d=0;d<b.length;d++)if(c=b[d][1].exec(window.navigator.userAgent)){a.browser=b[d][0];a.version=c[1];break}return a}();JSC3D.BinaryStream=function(a,b,c){b&&(this.isBigEndian=!0);this.data=a;this.offset=0;this.isIE=c};JSC3D.BinaryStream.prototype.size=function(){return this.data.length};JSC3D.BinaryStream.prototype.tell=function(){return this.offset};JSC3D.BinaryStream.prototype.seek=function(a){if(0>a||a>=this.data.length)return!1;this.offset=a;return!0};
JSC3D.BinaryStream.prototype.reset=function(){this.offset=0};JSC3D.BinaryStream.prototype.skip=function(a){this.offset=this.offset+a>this.data.length?this.data.length:this.offset+a};JSC3D.BinaryStream.prototype.available=function(){return this.data.length-this.offset};JSC3D.BinaryStream.prototype.eof=function(){return!(this.offset<this.data.length)};JSC3D.BinaryStream.prototype.readUInt8=function(){return this.decodeInt(1,!1)};
JSC3D.BinaryStream.prototype.readInt8=function(){return this.decodeInt(1,!0)};JSC3D.BinaryStream.prototype.readUInt16=function(){return this.decodeInt(2,!1)};JSC3D.BinaryStream.prototype.readInt16=function(){return this.decodeInt(2,!0)};JSC3D.BinaryStream.prototype.readUInt32=function(){return this.decodeInt(4,!1)};JSC3D.BinaryStream.prototype.readInt32=function(){return this.decodeInt(4,!0)};JSC3D.BinaryStream.prototype.readFloat32=function(){return this.decodeFloat(4,23)};
JSC3D.BinaryStream.prototype.readFloat64=function(){return this.decodeFloat(8,52)};JSC3D.BinaryStream.prototype.readBytes=function(a,b){var c=b;this.offset+b>this.data.length&&(c=this.data.length-this.offset);if(this.isIE)for(var d=0;d<c;d++)a[d]=this.data[this.offset++];else for(d=0;d<c;d++)a[d]=this.data[this.offset++].charCodeAt(0)&255;return c};
JSC3D.BinaryStream.prototype.decodeInt=function(a,b){if(this.offset+a>this.data.length)return this.offset=this.data.length,NaN;var c=[];this.readBytes(c,a);this.isBigEndian&&c.reverse();for(var d=0,e=1,f=0;f<a;f++)d+=c[f]*e,e*=256;b&&d&Math.pow(2,8*a-1)&&(d-=Math.pow(2,8*a));return d};
JSC3D.BinaryStream.prototype.decodeFloat=function(a,b){if(this.offset+a>this.data.length)return this.offset=this.data.length,NaN;var c=[];this.readBytes(c,a);this.isBigEndian&&c.reverse();var d=8*a-b-1,e=(1<<d)-1,f=e>>1,g=a-1,h=c[g];g+=-1;var k=-7,l=h&(1<<-k)-1;h>>=-k;for(k+=d;0<k;)l=256*l+c[g],g+=-1,k-=8;d=l&(1<<-k)-1;l>>=-k;for(k+=b;0<k;)d=256*d+c[g],g+=-1,k-=8;switch(l){case 0:l=1-f;break;case e:return d?NaN:Infinity*(h?-1:1);default:d+=Math.pow(2,b),l-=f}return(h?-1:1)*d*Math.pow(2,l-b)};
JSC3D.LoaderSelector={registerLoader:function(a,b){"function"==typeof b&&(JSC3D.LoaderSelector.loaderTable[a]=b)},getLoader:function(a){a=JSC3D.LoaderSelector.loaderTable[a.toLowerCase()];if(!a)return null;try{var b=new a}catch(c){b=null}return b},loaderTable:{}};var SmorfLoader=SmorfLoader||{};SmorfLoader=function(a,b,c,d){this.IE=!1};SmorfLoader.prototype.abort=function(){this.request&&(this.request.abort(),this.request=null)};
SmorfLoader.prototype.loadFromUrl=function(a,b){var c=this,d="ie"==JSC3D.PlatformInfo.browser,e=new XMLHttpRequest;e.open("GET",a,!0);d?e.setRequestHeader("Accept-Charset","x-user-defined"):e.overrideMimeType("text/plain; charset=x-user-defined");e.onreadystatechange=function(){if(4==this.readyState){if(200==this.status||0==this.status){if(c.onload){if(c.onprogress)c.onprogress("Loading Smorf file ...",1);if(d){var e=new JSC3D.Scene;try{c.parseSmorf(e,String.fromCharCode.apply(null,(new VBArray(this.responseBody)).toArray()),
!1,b)}catch(g){}}else e=new JSC3D.Scene,c.parseSmorf(e,this.responseText,!1,b);c.onload(e)}}else if(c.onerror)c.onerror('Failed to load Smorf file "'+a+'".');c.request=null}};this.onprogress&&(this.onprogress("Loading SmorfL file ...",0),e.onprogress=function(a){c.onprogress("Loading Smorf file ...",a.position/a.totalSize)});this.request=e;e.send()};