var PHP_DIR="php/";function appletActive(){active=!1;try{active=document.smorf.isActive()}catch(a){}return active}
function leesFile(a,b){smorf.loadFile(a+".smorf.bin",b);rotate=!0;void 0!=$("link")&&(hostname=window.location.hostname,pathname=window.location.pathname,pathname.substring(0,1),url="http://"+hostname+pathname+"?crystal="+a,urltxt=hostname+""+pathname+"?crystal="+a,0<urltxt.indexOf("crystals_")&&(arr=urltxt.split("?"),urltxt=arr[0]+"?<br>"+arr[1]),link='Link: <a href="'+url+'">'+urltxt+"</a>",Element.update($("link"),link))}
function ajax_getRandomFilenaam(){new Ajax.Request(PHP_DIR+"getRandomFilenaam.php",{method:"post",onSuccess:function(a){a=a.responseText||"no response text";leesFile(a);ajax_setmineraltext(a)}});document.getElementById("button_history").value="Show history"}function ajax_setmineraltext(a){new Ajax.Request(PHP_DIR+"getmineraltext.php?filenaam="+a,{method:"post",onSuccess:function(a){a=a.responseText||"";Element.update($("naam"),a)}})}
function ajax_getSearch(){terms=$("searchtextbox").value;"Enter search terms, then click the search button"==terms&&alert("Please enter your search terms, separated by spaces, in the text box below.");new Ajax.Request(PHP_DIR+"ajax_getSelectsSelectie.php?column=search&value="+terms,{method:"post",onSuccess:function(a){a=a.responseText||"no response text";Element.update($("selects_selectie"),a)}});resetSelects();document.getElementById("button_history").value="Show history"}
function ajax_selectbox(a,b){new Ajax.Request(PHP_DIR+"ajax_getSelectsSelectie.php?column="+a+"&value="+b,{method:"post",onSuccess:function(a){a=a.responseText||"no response text";Element.update($("selects_selectie"),a)}});resetSelects(a)}function ajax_session_add_filenaam(a){new Ajax.Request(PHP_DIR+"session_add_filenaam.php?filenaam="+a,{method:"post",onSuccess:function(a){}})}
function ajax_getSessionFilenamen(){"Clear history"==document.getElementById("button_history").value?(document.getElementById("button_history").value="Clear history",new Ajax.Request(PHP_DIR+"ajax_getSelectsSelectie.php?column=session&value=clear",{method:"post",onSuccess:function(a){a=a.responseText||"no response text";Element.update($("selects_selectie"),a)}})):(new Ajax.Request(PHP_DIR+"ajax_getSelectsSelectie.php?column=session&value=getfilenamen",{method:"post",onSuccess:function(a){a=a.responseText||
"no response text";Element.update($("selects_selectie"),a)}}),resetSelects(),document.getElementById("button_history").value="Clear history")}function ajax_logcrystal(a){new Ajax.Request(PHP_DIR+"logcrystal.php?filenaam="+a,{method:"post",onSuccess:function(a){}})}
function resetSelects(a){"minnaam"!=a&&(document.getElementById("mineral").selectedIndex=0);"v.id"!=a&&(document.getElementById("location").selectedIndex=0);"puntgroep"!=a&&(document.getElementById("puntgroep").selectedIndex=0);document.getElementById("button_history").value="Show history"}var bShowWireframe=!0,display="solid",olddisplay="solid",bShowSticks=!1,bShowTexture=!1,bShowMillers=!1,bShowAxes=!1,transparency=.6,rotate=!1;
function toggleWireframe(){bShowWireframe=!bShowWireframe;smorf.showWireframe(bShowWireframe)}function toggleTexture(){(bShowTexture=!bShowTexture)?smorf.displaySticks():(smorf.displaySolid(),bShowWireframe||smorf.showWireframe(!1))}function toggleSticks(){(bShowSticks=!bShowSticks)?smorf.displaySticks():(smorf.displaySolid(),bShowWireframe||smorf.showWireframe(!1))}function toggleMillers(){bShowMillers=!bShowMillers;smorf.showMillers(bShowMillers)}
function toggleAxes(){bShowAxes=!bShowAxes;smorf.showAxes(bShowAxes)}function zoomIn(){smorf.zoom(!0)}function zoomOut(){smorf.zoom(!1)}function incTransparency(){transparency+=.2;1<transparency&&(transparency=0);smorf.setTransparency(transparency)}function toggleRotation(){(rotate=!rotate)?smorf.autoRotate(-2,100):smorf.stopAutoRotate()}function zoomInMillers(){bShowMillers&&smorf.zoomMillers(!0)}function zoomOutMillers(){bShowMillers&&smorf.zoomMillers(!1)}
function toggleTexture(){(bShowTexture=!bShowTexture)?smorf.displayTextured():(smorf.displaySolid(),bShowWireframe||smorf.showWireframe(!1))}function setA(){smorf.viewAlongAxis("a")}function setB(){smorf.viewAlongAxis("b")}function setC(){smorf.viewAlongAxis("c")}function svg(){smorf.saveGif()};