/*
 Copyright (c) 2013-2018 M.H.P.C. Holtkamp, Waddinxveen, The Netherlands.
 Version 1.42
 Website: www.smorf.nl
*/
JSC3D.Scene.prototype.millers=[];JSC3D.Scene.prototype.addMiller=function(L){this.millers.push(L)};JSC3D.Scene.prototype.alfa=0;JSC3D.Scene.prototype.beta=0;JSC3D.Scene.prototype.gamma=0;var Smorf=Smorf||{};
Smorf=function(L){var t=[];t.filename=null;t.rotation=null;t.files_directory=null;t.backgroundcolor=null;t.axes=null;var c=new JSC3D.Viewer(L),M=null,y,P=null,u=null,N=null,H=!1,C=!1,B=!0,Q=!1,w=.25,I=14,aa="a -a b -b c -c".split(" "),ba="a1 -a1 a2 -a2 c -c -a3 a3".split(" "),R=!1,O=!1,D="",z=null;c.onmousedown=function(a,b,f,g,e){z&&(clearInterval(z),z=null)};c.beforeupdate=function(){if(null!=this.scene){y=this.scene.getChild(0);y.material.transparency=w;P=this.scene.getChild(2);P.visible=B;u=this.scene.getChild(3);
    u.visible=C;if("a"==D||"b"==D||"c"==D)D="";Q?(y=this.scene.getChild(0),y.material.usePalettes=!0,mesh2=this.scene.getChild(1),mesh2.material.usePalettes=!0):(y=this.scene.getChild(0),y.material.usePalettes=!1,mesh2=this.scene.getChild(1),mesh2.material.usePalettes=!1)}};c.afterupdate=function(){if(null!=this.scene){u=this.scene.getChild(3);if(u.visible){var a=24==u.vertexBuffer.length?ba:aa;for(var b=0;b<a.length;b++)Y(a[b],"",u.transformedVertexBuffer[3*b],u.transformedVertexBuffer[3*b+1],u.transformedVertexBuffer[3*
b+2],"#0000ff","bold 16px courier",16,1.15,!1)}N=this.scene.getChild(4);if(H)for(a=0;2*a<this.scene.millers.length;a++)Y(this.scene.millers[2*a],this.scene.millers[2*a+1],N.transformedVertexBuffer[3*a],N.transformedVertexBuffer[3*a+1],N.transformedVertexBuffer[3*a+2],"yellow","bold "+I+"px courier",I,1.01,!0)}};c.keyUpHandler=function(a){16==a.keyCode&&(O=R=!1)};c.keyDownHandler=function(a){switch(a.keyCode){case 16:R=!0;break;case 18:O=!0;break;case 87:B=!B;break;case 77:H=!H;break;case 75:C=!C;
    break;case 107:case 61:O?I++:c.zoomFactor*=1.2;break;case 109:case 173:O?I--:c.zoomFactor/=1.2;break;case 82:case 114:autoRotate=!autoRotate;break;case 84:w=R?w-.1:w+.1;0>w&&(w=.5);.5<w&&(w=0);break;case 49:D="a";break;case 50:D="b";break;case 51:D="c"}c.update(!1);return!0};var Z=function(a,b){a.rotMatrix.identity();if("a"==b||"b"==b){var f=a.scene.getChild(3);var g="b"==b?6:0;var e=f.vertexBuffer[g];var h=f.vertexBuffer[g+2];e=(0*e+1*h)/(Math.sqrt(e*e+h*h)*Math.sqrt(1));e=1<e?0:-1>e?Math.PI:Math.acos(e);
    e=180*e/Math.PI;0<f.vertexBuffer[g]&&(e=-e);a.rotate(0,e,0);f=90-180*("b"==b?a.scene.alfa:a.scene.beta)/Math.PI;a.rotate(f,0,0)}"c"==b&&a.rotate(90,0,0)};this.getSTL=function(){let a="solid smorf\n",b=y.indexBuffer,f=0,g=1,e=2,h=y.faceNormalBuffer,r=0,k=y.vertexBuffer,d;for(;e<b.length;){for(;-1!=b[e];)a+="facet normal "+h[r].toFixed(4)+" "+h[r+1].toFixed(4)+" "+h[r+2].toFixed(4)+"\nouter loop\n",d=3*b[f],a+="vertex "+k[d].toFixed(4)+" "+k[d+1].toFixed(4)+" "+k[d+2].toFixed(4)+"\n",d=3*b[g],a+="vertex "+
    k[d].toFixed(4)+" "+k[d+1].toFixed(4)+" "+k[d+2].toFixed(4)+"\n",d=3*b[e],a+="vertex "+k[d].toFixed(4)+" "+k[d+1].toFixed(4)+" "+k[d+2].toFixed(4)+"\n",a+="endloop\nendfacet\n",g++,e++;f=e+1;g=f+1;e=g+1;r+=3}return a+"endsolid smorf\n"};var Y=function(a,b,f,g,e,h,r,k,d,x){if(void 0!=a){var m=1;"low"==c.definition&&(m=2);"high"==c.definition&&(m=.5);var J=L.width/2,A=L.height/2;f=~~(J+d*(f*m-J));g=~~(A+d*(g*m-A));e=~~(d*e*m);d=~~g;m=1;"low"==c.definition&&(m=.5,1==d%2&&d++);"high"==c.definition&&(m=
    2);c.zBuffer[~~(m*d*c.frameWidth)+~~(m*~~f)]>m*~~e+10||(c.ctx.font=r,c.ctx.textAlign="center",x&&(c.ctx.fillStyle="black",c.ctx.fillText(a,f+1,1+g+~~(k/4)),""!=b.trim()&&c.ctx.fillText(b,f+1,1+g+k/2-k/2-4)),c.ctx.fillStyle=h,c.ctx.fillText(a,f,g+~~(k/4)),""!=b.trim()&&c.ctx.fillText(b,f,g+k/2-k/2-4))}};this.setParameter=function(a,b){t[a]=b};this.init=function(){C=t.axes||!1;M=t.files_directory||"";c.setParameter("InitRotationY",-18.43);c.setParameter("InitRotationX",9.47);c.setParameter("InitRotationZ",
    0);c.setParameter("BackgroundColor1",t.backgroundcolor||"#FFFFFF");c.setParameter("BackgroundColor2",t.backgroundcolor||"#FFFFFF");c.setParameter("RenderMode","flat");c.setParameter("Definition",t.definition||"standard");c.init();c.update();null!=t.filename&&this.loadFile(t.filename);null!=t.rotation&&this.autoRotate(t.rotation/10,100)};this.setDefinition=function(a){c.setDefinition(a)};this.viewAlongAxis=function(a){Z(c,a);c.update(!1)};this.viewClinographic=function(){this.stopAutoRotate();Z(c,
    "c");c.rotate(-90,0,0);c.rotate(0,-18.43,0);c.rotate(9.47,0,0);c.update()};this.loadFile=function(a,b){P=null;null!=M&&""!=M&&(a=M+"/"+a);c.replaceSceneFromUrl(a,b);c.lastRotX=0;c.lastRotY=0;c.update(!1)};this.loadScene=function(a,b){var f=null;1==b&&(f=c.rotMatrix.getCopy());c.replaceScene(a);c.lastRotX=0;c.lastRotY=0;c.update(!1);1==b?c.rotMatrix=f:this.viewClinographic()};this.autoRotate=function(a,b){if(!z){clearInterval(z);var f=this;z=setInterval(function(){f.rotatec(a);f.update()},b)}};this.stopAutoRotate=
    function(){z&&(clearInterval(z),z=null)};this.toggleLines=function(){B=!B;c.update(!1)};this.showWireframe=function(a){B=a;c.update(!1)};this.toggleWireframe=function(){B=!B;c.update(!1)};this.toggleAxes=function(){C=!C;c.update(!1)};this.showAxes=function(a){C=a;c.update(!1)};this.toggleMillers=function(){H=!H;c.update(!1)};this.toggleFormColors=function(){Q=!Q;c.update()};this.showMillers=function(a){H=a;c.update(!1)};this.setTransparency=function(a){w=a/2;0>w&&(w=0);.5<w&&(w=.5);c.update(!1)};
    this.zoom=function(a){var b=1.2;a||(b=1/b);c.zoomFactor*=b;c.update(!1)};this.zoomMillers=function(a){a?I++:I--;c.update(!1)};this.rotate=function(a,b,f){c.rotate(a,b,f)};this.update=function(a){c.update(a)};this.resize=function(a,b){c.canvas.width=a;c.canvas.height=b;c.init();c.update()};this.rotatec=function(a){a*=Math.PI/180;var b=Math.cos(a);a=Math.sin(a);var f=u.transformedVertexBuffer[12]-u.transformedVertexBuffer[15],g=-u.transformedVertexBuffer[13]+u.transformedVertexBuffer[16],e=u.transformedVertexBuffer[14]-
        u.transformedVertexBuffer[17],h=Math.sqrt(f*f+g*g+e*e);f/=h;g/=h;e/=h;h=new JSC3D.Matrix3x4;h.m00=b+f*f*(1-b);h.m01=f*g*(1-b)-e*a;h.m02=f*e*(1-b)+g*a;h.m03=0;h.m10=g*f*(1-b)+e*a;h.m11=b+g*g*(1-b);h.m12=g*e*(1-b)-f*a;h.m13=0;h.m20=e*f*(1-b)-g*a;h.m21=e*g*(1-b)+f*a;h.m22=b+e*e*(1-b);h.m23=0;c.rotMatrix.multiply(h);c.update(!1)};SmorfLoader.prototype.parseSmorf=function(a,b,f,g){var e=new JSC3D.Mesh;e.isDoubleSided=!1;e.vertexBuffer=[];e.indexBuffer=[];e.faceNormalBuffer=[];var h=new JSC3D.Mesh;h.isDoubleSided=
        !1;h.vertexBuffer=[];h.indexBuffer=[];h.faceNormalBuffer=[];var r=new JSC3D.Mesh;r.isDoubleSided=!1;r.vertexBuffer=[];r.indexBuffer=[];r.faceNormalBuffer=[];var k=new JSC3D.Mesh;k.isDoubleSided=!1;k.vertexBuffer=[];k.indexBuffer=[];k.faceNormalBuffer=[];var d=new JSC3D.BinaryStream(b,!0,f),x=d.readFloat32();a.alfa=x;var m=d.readFloat32();a.beta=m;var J=d.readFloat32();a.gamma=J;b=d.readInt16();f=d.readInt16();var A=d.readInt16();d.readFloat32();for(var v=d.readInt16(),p=0;p<v;p++){var q=d.readFloat32();
        var l=d.readFloat32();var n=-d.readFloat32();e.vertexBuffer.push(q,l,n);h.vertexBuffer.push(q,l,n);r.vertexBuffer.push(q,l,n)}v=d.readInt16();for(p=0;p<v;p++){q=d.readInt16();l=d.readInt16();n=d.readInt16();var K=d.readInt16();h.indexBuffer.push(q,l,n,K,-1);e.indexBuffer.push(q,K,n,l,-1)}v=d.readInt16();for(p=0;p<v;p++)q=d.readInt16(),l=d.readInt16(),n=d.readInt16(),h.indexBuffer.push(q,l,n,-1),e.indexBuffer.push(q,n,l,-1);n=d.readInt16();for(p=0;p<n;p++){q=d.readInt16();l=d.readInt16();do r.indexBuffer.push(q,
        l,q,-1),l=d.readInt16();while(-1!=l)}a.millers=[];v=d.readInt16();for(p=0;p<v;p++){var E=d.readInt8(),F=d.readInt8(),G=d.readInt8();q=d.readFloat32();l=d.readFloat32();n=d.readFloat32();if(!(0==E&&0==F&0==G)){K=Math.abs(E);var S=Math.abs(F),T=Math.abs(G),U="",V="",W="",X="";9<K&&(U=".",W=" ");9<S&&(V=U=".",X=W=" ");9<T&&(V=".",X=" ");E=0>E?"-":" ";9<K&&(E+=E);F=0>F?"-":" ";9<S&&(F+=F);G=0>G?"-":" ";9<T&&(G+=G);a.addMiller(K+U+S+V+T);a.addMiller(E+W+F+X+G);k.vertexBuffer.push(1.01*q,1.01*l,-1.01*n)}}k.indexBuffer.push(0,
        1,2,-1);k.visible=!1;p=Math.sin(x);q=Math.cos(x);l=Math.cos(m);n=(Math.cos(J)-l*q)/p;v=Math.sqrt(1-n*n-l*l);n*=1.5;l*=1.5;v*=1.5;p*=1.5;q*=1.5;d=new JSC3D.Mesh;d.isDoubleSided=!1;d.vertexBuffer=[];d.indexBuffer=[];d.faceNormalBuffer=[];d.visible=!1;d.vertexBuffer.push(1.05*n,1.05*l,1.05*v);d.vertexBuffer.push(1.05*-n,1.05*-l,1.05*-v);d.vertexBuffer.push(1.05*p,1.05*q,0);d.vertexBuffer.push(1.05*-p,1.05*-q,-0);d.vertexBuffer.push(0,1.5*1.05,0);d.vertexBuffer.push(-0,-1.5*1.05,-0);d.indexBuffer.push(0,
        1,0,-1,2,3,2,-1,4,5,4,-1);1E-4>Math.abs(x-1.5708)&&1E-4>Math.abs(m-1.5708)&&1E-4>Math.abs(J-2.0944)&&(d.vertexBuffer.push(-n,l,v,n,-l,-v),d.indexBuffer.push(6,7,6,-1));x=new JSC3D.Material;m=255-b;255-A<m&&(m=255-A);255-f<m&&(m=255-f);b+=m;255<b&&(b=255);A+=m;255<A&&(A=255);f+=m;255<f&&(f=255);b=65536*b+256*f+A;x.diffuseColor=b;x.diffuseColor=void 0!==g&&g.facecolor?g.facecolor:b;x.transparency=.2;e.material=x;b=new JSC3D.Material;b.diffuseColor=x.diffuseColor;b.transparency=0;h.material=b;b=new JSC3D.Material;
        b.diffuseColor=void 0!==g&&g.edgecolor?g.edgecolor:0;b.ambientColor=void 0!==g&&g.edgecolor?g.edgecolor:0;b.transparency=0;r.material=b;g=new JSC3D.Material;g.diffuseColor=255;g.ambientColor=255;g.transparency=0;d.material=g;e.calcFaceNormals();a.addChild(e);h.calcFaceNormals();a.addChild(h);r.renderMode="wireframe";r.calcFaceNormals();a.addChild(r);d.renderMode="wireframe";d.calcFaceNormals();a.addChild(d);k.calcFaceNormals();a.addChild(k)};JSC3D.LoaderSelector.registerLoader("bin",SmorfLoader)};